### ISSUE TITLE
Szyfrowanie hasła dla bazy danych

### ISSUE THREAD

**Issue by kkwasnik** [cojot/SGGW#16]
Trzeba stworzyć metode, która przy rejestracji będzie szyfrowała wpisane przez użytkownika hasło np. mda5 lub sha 256, nastepnie zapisywała je tak  do bazy.

**Comment by kkwasnik** [comment]
zrobicie to we dwóch ;)

**Comment by PatrykMackowski** [comment]
Zrobione za pomoca sha-256
