### ISSUE TITLE
DB - Prosze o wybranie produktow i dodanie do bazy danych

### ISSUE THREAD

**Issue by cojot** [cojot/SGGW#17]
Co bedziemy sprzedawac.

**Comment by cojot** [comment]
Czy produkty zostały juz wybrane i dodane do bazy?

**Comment by agnes54b** [comment]
Adam Zawiska powinien dodać niedługo

**Comment by kkwasnik** [comment]
Przepraszam za zwłokę. Już dodane. Zamykam case.

**Comment by aksiwaz** [comment]
Wprowadzam zmiany i zamykam.
